kind: pipeline
type: kubernetes
name: default

steps:
  - name: plan
    image: hashicorp/terraform:light
    environment:
      KUBE_CLUSTER_CERT:
        from_secret: KUBE_CLUSTER_CERT
      KUBE_CLIENT_CERT:
        from_secret: KUBE_CLIENT_CERT
      KUBE_CLIENT_KEY:
        from_secret: KUBE_CLIENT_KEY
    commands:
      - sed -i "s/KUBE_CLUSTER_CERT/$KUBE_CLUSTER_CERT/g" kube_config.yml
      - sed -i "s/KUBE_CLIENT_CERT/$KUBE_CLIENT_CERT/g" kube_config.yml
      - sed -i "s/KUBE_CLIENT_KEY/$KUBE_CLIENT_KEY/g" kube_config.yml
      - terraform init -input=false
      - terraform plan -out tfapply

trigger:
  branch:
    - main
  event:
    - push
    - pull_request

---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: plan
    image: hashicorp/terraform:light
    environment:
      KUBE_CLUSTER_CERT:
        from_secret: KUBE_CLUSTER_CERT
      KUBE_CLIENT_CERT:
        from_secret: KUBE_CLIENT_CERT
      KUBE_CLIENT_KEY:
        from_secret: KUBE_CLIENT_KEY
    commands:
      - sed -i "s/KUBE_CLUSTER_CERT/$KUBE_CLUSTER_CERT/g" kube_config.yml
      - sed -i "s/KUBE_CLIENT_CERT/$KUBE_CLIENT_CERT/g" kube_config.yml
      - sed -i "s/KUBE_CLIENT_KEY/$KUBE_CLIENT_KEY/g" kube_config.yml
      - terraform init -input=false
      - terraform apply -auto-approve tfapply

trigger:
  target:
    - production
  event:
    - promote
